OPENAI_API_KEY = "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"
SERP_API_KEY = "a60854dad2c2be3f60ba344f67ae365664141131ad2a9d6b30441367c1db3afb"
PINECONE_KEY = "07bb24f0-6adb-4321-a3a2-388ccff219d4"
PINECONE_ENV = "us-east1-gcp"
APIFY_KEY = "apify_api_DAuTOYy3vuiMeSDEjptT1jPgtTH2oU0AEYpC"