OPENAI_API_KEY = "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"
SERP_API_KEY = "a60854dad2c2be3f60ba344f67ae365664141131ad2a9d6b30441367c1db3afb"
PINECONE_API_KEYs = "7fd8933e-3910-4781-9326-e9c1cfe3070a"
PINECONE_ENV = "us-east1-gcp"
APIFY_KEY = "apify_api_DAuTOYy3vuiMeSDEjptT1jPgtTH2oU0AEYpC"