oai-key = "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"
pinecone-key = "07bb24f0-6adb-4321-a3a2-388ccff219d4"
pinecone-env = "us-east1-gcp"
apify-key = "apify_api_DAuTOYy3vuiMeSDEjptT1jPgtTH2oU0AEYpC"